name: 'BukkitSnake'
main: com.bringholm.bukkitsnake.BukkitSnake
version: '1.0'
softdepend: [ProtocolLib]
author: 'AlvinB'
commands:
  snake:
    description: Activates the snake chat game.
    usage: /snake
